const ht = [
    'Kyte Baby Printed Sleep Bag 1 TOG (Persimmon)',
    'Kyte Baby Printed Sleep Bag 1 TOG (Pumpkin)',
    'Kyte Baby Sleep Bag 2.5 TOG (Dahlia)',
    'Kyte Baby Sleep Bag 2.5 TOG (Eggplant)',
    'Kyte Baby Sleep Bag 2.5 TOG (Baltic)',
    'Kyte Baby Sleep Bag 2.5 TOG (Olive)',
    'Kyte Baby Sleep Bag 2.5 TOG (Nutmeg)',
    'Kyte Baby Sleep Bag 2.5 TOG (Clementine)',
    'Kyte Baby Printed Sleep Bag 2.5 TOG (Fig)',
    'Kyte Baby Printed Sleep Bag 2.5 TOG (Persimmon)',
    'Kyte Baby Printed Sleep Bag 2.5 TOG (Pumpkin)',
    'Kyte Baby Sleep Bag 1 TOG (Dahlia)',
    'Kyte Baby Sleep Bag 1 TOG (Eggplant)',
    'Kyte Baby Sleep Bag 1 TOG (Baltic)',
    'Kyte Baby Sleep Bag 1 TOG (Olive)',
    'Kyte Baby Sleep Bag 1 TOG (Nutmeg)',
    'Kyte Baby Sleep Bag 1 TOG (Clementine)',
    'Kamik Rapha Winter Boot (Black)',
    'Calikids Knit Headband (Beige)',
    'Calikids Knit Headband (Pink)',
    'Calikids Knit Headband (Grey)',
    'Calikids Mom & Me Knit Winter Hat (Black)',
    'Calikids Mom & Me Knit Winter Hat (Cream)',
    'Calikids Knit Cashmere Touch Winter Hat (Grey)',
    'Calikids Knit Cashmere Touch Winter Hat (Brick)',
    'Calikids Knit Cashmere Touch Winter Hat (Blue)',
    'Calikids Knit Cashmere Touch Winter Hat (Iron)',
    'Calikids Cotton Knit Mitten (Grey Mix)',
    'Calikids Cotton Knit Mitten (Pink Mix)',
    'Calikids Balaclava (Black)',
    'Calikids Balaclava (Cabaret Pink)',
    'Calikids Balaclava (Graphite)',
    'Calikids Newborn Knit Hat (Grey Mix)',
    'Calikids Newborn Knit Hat (Cream Mix)',
    'Calikids Knit Double Pompom Hat (Grey Mix)',
    'Calikids Cotton Knit Pompom Hat (Brick Mix)',
    'Calikids Cotton Knit Pompom Hat (Pink Mix)',
    'Calikids Cotton Knit Pompom Hat (Charcoal Mix)',
    'Calikids Cotton Knit Winter Hat (Graphite)',
    'Calikids Baby Mitt with String (Red)',
    'Calikids Baby Mitt with String (Charcoal)',
    'Calikids Baby Mitt with String (Denim Blue)',
    'Calikids Mitten with Clips (Red)',
    'Calikids Mitten with Clips (Cabaret Pink)',
    'Calikids Mitten with Clips (Denim Blue)',
    'Thermos FUNtainer Stainless Steel Food Jar 10oz (Purple)',
    'Jellycat Bashful Beau Bunny Soother',
    'Calikids Long Cuff Mitten (Coyote)',
    'Calikids Long Cuff Mitten (Scooter Red)',
    'Calikids Long Cuff Mitten (Denim Blue)',
    'Calikids Long Cuff Mitten (Cabaret Pink)',
    'Jellycat Storm Octopus (Large)',
    'Jellycat If I Were A Lion Book',
    'Boon Snug Straw Silicone Straw Lids 3-Pack (Mint)',
    'Skip Hop Doubleplay Reversible Play Mat (Little Travelers)',
    'Skip Hop Moby Smart Sling 3-Stage Tub (Grey)',
    'Baby Bjorn Play Yard Light (Dark Blue Mesh)',
    'Baby Bjorn Play Yard Light (Silver Mesh)',
    'Baby Bjorn Play Yard Light (Black Mesh)',
    'Bruder CAT Track Loader',
    'Bravado Body Silk Seamless Full Cup Nursing Bra 2.0 (Butterscotch)',
    'Bravado Body Silk Seamless Full Cup Nursing Bra 2.0 (Black)',
    'Bravado Body Silk Seamless Nursing Bra 2.0 (Silver Belle)',
    'Bravado Body Silk Seamless Nursing Bra 2.0 (Butterscotch)',
    'Bravado Body Silk Seamless Nursing Bra 2.0 (Black)',
    'Kyte Baby Bamboo Single Swaddle (Sage)',
    'Kyte Baby Bamboo Single Swaddle (Navy)',
    'Aden + Anais Classic Dream Blanket (Picked For You)',
    'Aden + Anais Silky Soft Dream Blanket (Watercolour Garden Roses)',
    'Aden + Anais Silky Soft Swaddle Set 3-Pack (Expedition)',
    'Aden + Anais Silky Soft Dream Blanket (Expedition)',
    'Aden + Anais Snuggle Knit Single Swaddle (Rosettes)',
    'Aden + Anais Snuggle Knit Single Swaddle (Navy Stripe)',
    'Aden + Anais Snuggle Knit Single Swaddle (Heather Grey)',
    'Aden + Anais Snuggle Knit Multi Use Cover (Navy Stripe)',
    'Aden + Anais Classic Single Swaddle (Paisley Teal Paisley Drop)',
    'Aden + Anais Classic Single Swaddle (Around The World Map)',
    'Aden + Anais Classic Single Swaddle (Forest Fantasy Flowers)',
    'Kyte Baby Change Pad Cover (Midnight)',
    'Kyte Baby Change Pad Cover (Blush)',
    'Aden + Anais Silky Soft Swaddle Set 3-Pack (Watercolour Garden)',
    'Aden + Anais Silky Soft Single Swaddle (Golden Sun)',
    'Aden + Anais White Label Silky Soft Single Swaddle (Watercolour Garden Roses)',
    'Aden + Anais Classic Single Swaddle (Dahlias Sparrow)',
    'Kyte Baby Bundler (Oat)',
    'Aden + Anais Snuggle Knit Lovey (Heather Grey)',
    'Kyte Baby Bundler (Midnight)',
    'Calikids Cotton Knit Winter Hat (Black)',
    'Calikids Mitten with Clips (Black)',
    'Babyfied Apparel Beanie (Light Grey)',
    'Babyfied Apparel Beanie (Black)',
    'Jellycat Fuddlewuddle Pig (Medium)',
    'Jellycat Little Kitten',
    'Jellycat If I Were A Sloth Book',
    'Jellycat Elly Ballerina Book',
    'Jellycat Fuddlewuddle Lion (Medium)',
    'Jellycat Fuddlewuddle Puppy (Medium)',
    'KicKee Pants Print Swaddling Blanket (Natural Hearts)',
    'KicKee Pants Print Swaddling Blanket (Cow Print)',
    'KicKee Pants Print Knot Hat (Cow Print)',
    "KicKee Pants Women's Long Sleeve Loosey Goosey Pajama Set (Natural Hearts)",
    'KicKee Pants Training Pants Set (Strawberry/Natural)',
    'KicKee Pants Training Pants Set (Midnight/Natural)',
    'KicKee Pants Boxer Brief (Slate Guitars & Stars)',
    'KicKee Pants Boxer Brief (Fairground Stripe)',
    'KicKee Pants Boxer Brief (Cow Print)',
    'KicKee Pants Print Long Sleeve Pajama Set (Natural Hearts)',
    'KicKee Pants Underwear (Natural Dahlias)',
    'KicKee Pants Underwear (Cotton Candy Stripe)',
    'KicKee Pants Print Footie with Zipper (Natural Hearts)',
    'KicKee Pants Print Footie with Zipper (Slate Guitars & Stars)',
    'KicKee Pants Print Footie with Zipper (Natural Dahlias)',
    'KicKee Pants Print Footie with Zipper (Cow Print)',
    'KicKee Pants Solid Footie with Zipper (Wild Strawberry)',
    'KicKee Pants Solid Footie with Zipper (Slate)',
    'KicKee Pants Solid Footie with Zipper (Strawberry)',
    'KicKee Pants Print Coverall with Zipper (Fairground Stripe)',
    'KicKee Pants Print Coverall with Zipper (Cotton Candy Stripe)',
    'KicKee Pants Long Sleeve Graphic Tee Pajama Set (Slate Guitars & Stars)',
    'KicKee Pants Print Long Sleeve Pajama Set (Cow Print)',
    'KicKee Pants Solid Footie with Zipper (Navy)',
    'UPPAbaby Changing Backpack (Noa - Navy)',
    'UPPAbaby Travel Bag (Knox/Alta)',
    'UPPAbaby Knox Cup Holder',
    'Boon Soak 3-Stage Bathtub (Grey)',
    'Minimal Insulated Food Jar V2 500ml (Classic)',
    'Minimal Insulated Food Jar V2 500ml (White)',
    'Minimal Insulated Food Jar V2 500ml (Limpet)',
    'Minimal Insulated Food Jar V2 500ml (Rose)',
    'UPPAbaby Cozy Ganoosh (Noa)',
    'UPPAbaby Cozy Ganoosh (Declan)',
    'UPPAbaby Cozy Ganoosh (Jordan)',
    'UPPAbaby Cozy Ganoosh (Gregory)',
    'UPPAbaby Cozy Ganoosh (Emmett)',
    'UPPAbaby Changing Backpack (Greyson - Charcoal Melange)',
    'Matchstick Monkey Original Teething Toy (Mint Green)',
    'Matchstick Monkey Original Teething Toy (Pink)',
    'Headster Kids Colocroco Cap',
    'Headster Kids Ti-Loup Cap',
    'Headster Kids Tie Dye Pink Cap',
    'Headster Kids Sis Cap',
    'Headster Kids Tropic Pink Cap',
    'Headster Kids Original Camo Cap',
    'Só Luxury Sweet Island Coconut (250ml)',
    'Só Luxury Sweet Bergamot Lime (250ml)',
    'Headster Kids Fine Foliage True Indigo Cap',
    'Headster Kids Varsity Fuchsia Cap',
    'Headster Kids Vacay Cap',
    'Headster Kids Fresh Bloom Cap',
    'Headster Kids Leafy Cap',
    'Headster Kids City Grey Cap',
    'Headster Kids City Camo Cap',
    'Só Luxury Sweet Vanilla Mint Coffee (250ml)',
    'Minimal Insulated Food Jar 500ml (White)',
    'Minimal Insulated Food Jar 500ml (Black)',
    'Minimal Insulated Food Jar 500ml (Classic)',
    'Petunia Pickle Bottom Boxy Backpack (Birch/Black)',
    'Jellycat Livi Leopard (Medium)',
    'Jellycat Bashful Flamingo (Medium)',
    'Jellycat Bashful Grey Bunny Soother',
    'Jellycat Bashful Lamb Soother',
    'Jellycat Bashful Dino (Medium)',
    'Jellycat Kitten Caboodle Black',
    'Jellycat Bashful Woodland Bunny (Medium)',
    'Jellycat Bashful Monkey (Small)',
    'Kyte Baby Sleeveless Romper (Melon)',
    'Kyte Baby Sleep Bag 2.5 TOG (Midnight)',
    'Kyte Baby Printed Sleep Bag 1 TOG (Succulent)',
    'Kyte Baby Scratch Mittens (Mushroom)',
    'Kyte Baby Printed Long Sleeve Romper (Aloe Rainbow)',
    'Kyte Baby Bib (Bubblegum)',
    'Kyte Baby Long Sleeve Bodysuit (Slate)',
    'Kyte Baby Long Sleeve Bodysuit (Storm)',
    'The OVer Company OVer Multi Use Cover (Davis)',
    'The OVer Company Butter Blanket (Lennon)',
    'The OVer Company OVer Multi Use Cover (Kelsey)',
    'The OVer Company OVer Multi Use Cover (Joy)',
    'The OVer Company Butter Blanket (Kelsey)',
    'The OVer Company OVer Multi Use Cover (Chase)',
    'The OVer Company Nodo Hat (Lennon)',
    'The OVer Company Nodo Gown (Poppy)',
    'The OVer Company OVer Multi Use Cover (Poppy)',
    'The OVer Company Butter Blanket (Poppy)',
    'The OVer Company Butter Blanket (Olive)',
    'The OVer Company Butter Blanket (Serene)',
    'The OVer Company Nodo Gown (Lane)',
    'The OVer Company OVer Multi Use Cover (Serene)',
    'The OVer Company OVer Multi Use Cover (Lane)',
    'The OVer Company OVer Multi Use Cover (Everett)',
    'The OVer Company Nodo Hat (Serene)',
    'The OVer Company Nodo Hat (Lane)',
    'The OVer Company Nodo Hat (Everett)',
    'The OVer Company Nodo Hat (Chase)',
    'The OVer Company Nodo Gown (Everett)',
    'The OVer Company OVer Multi Use Cover (Eclipse)',
    'The OVer Company Nodo Gown (Olive)',
    'The OVer Company Nodo Gown (Eclipse)',
    'The OVer Company OVer Multi Use Cover (Olive)',
    'The OVer Company Nodo Gown (Serene)',
    'Me & Henry Linden Henley (Mustard/White Stripe)',
    'Me & Henry Blaine Hooded Romper (Navy/Grey Multi)',
    'Me & Henry Harrison Cord Overalls (Navy)',
    'UPPAbaby Cruz V2 (Greyson - Charcoal Melange)',
    'The North Face Littles Box Logo Pom Beanie (TNF Black)',
    'The North Face Infant Thermoball Eco Bunting One Piece (Gardenia White)',
    'The North Face Infant Thermoball Eco Hoodie Jacket (Meld Grey)',
    'The North Face Toddler Reversible Perrito Jacket (Vanadis Grey)',
    'The North Face Toddler Mitt (TNF Black)',
    'The North Face Littles Bear Beanie (Gardenia White Polka Dot Floral Print)',
    'The North Face Littles Bear Beanie (Taupe Green Explorer Camo Print)',
    'The North Face Youth Montana Futurelight Mitt (TNF Black)',
    'The North Face Infant Surgent Crew Set (Niagara Blue)',
    'The North Face Youth Mudder Trucker Hat (TNF Light Grey Heather/Vanadis Grey)',
    'The North Face Infant Thermoball Eco Bunting One Piece (Meld Grey)',
    'Manhattan Toy Skwish Classic',
    'Nomi High Chair Tray (White)',
    'Kyte Baby Bamboo Single Swaddle (Emerald)',
    'Kyte Baby Bamboo Single Swaddle (Charcoal)',
    'Kyte Baby Bamboo Single Swaddle (Storm)',
    'Kyte Baby Bamboo Single Swaddle (Slate)',
    'Kyte Baby Bamboo Single Swaddle (Cloud)',
    'Mushie Stacking Cups Toy (Forest)',
    'Mushie Stacking Rings Toy (Original)',
    'The Mommy Light (Black)',
    'Matchstick Monkey Animal Teether (Gigi Giraffe)',
    'Babyfied Apparel Beanie (Ash Rose)',
    'Babyfied Apparel Beanie (Camel)',
    'Robeez Snap Bootie (Miles Ivory)',
    'Headster Kids Dino Cap',
    'Stride Rite Soft Motion Tonia Shoe (Purple)',
    'Stride Rite Soft Motion Splash Sandal (Navy/Orange)',
    'Headster Kids Varsity Sand Cap',
    'Headster Kids Callback Cap',
    'Jellycat Silly Succulent Columnar Cactus',
    'Jellycat Squishy Squash Green',
    'Jellycat Sensational Seafood Crab',
    'Jellycat Bashful Bee (Medium)',
    'Jellycat Bashful Cream Bunny (Medium)',
    'Jellycat Bashful Penguin (Medium)',
    'Jellycat Little Penguin',
    'Jellycat Cocoa Bear (Medium)',
    'Headster Kids Fall Flavours Cap',
    'Headster Kids Evertrolling Cap',
    'Headster Kids Hippie Dippie Cap',
    'Headster Kids Butterfly High Pink Cap',
    'Headster Kids Butterfly High Beige Cap',
    'Headster Kids Flower Child Rust Cap',
    'Headster Kids Flower Child Fuchsia Cap',
    'Jellycat Squishy Squash Yellow',
    'Stride Rite Made2Play Light-Up Neo Sneaker Wide (Grey/Lime)',
    'Stride Rite Soft Motion Kellen Sneaker Wide (Navy)',
    'Headster Kids Fly Racoon Cap',
    'Jellycat Rolie Polie Giraffe',
    'Jellycat Bashful Black & White Cat (Medium)',
    'Jellycat Fuddlewuddle Lion Soother',
    'Jellycat Sensational Seafood Lobster',
    'Stride Rite Soft Motion Milo Extra Wide (Navy)',
    'My Carry Potty (The Grey Potty)',
    'My Carry Potty (The Ladybird Potty)',
    'Nuna MIXX (Riveted)',
    'SmartWool Hike Light Ankle Socks 1-Pack (Military Olive)',
    'SmartWool Hike Light Ankle Socks 1-Pack (Medium Gray)',
    'SmartWool Hike Light Crew Socks 1-Pack (Charcoal)',
    'SmartWool Hike Light Crew Socks 1-Pack (Potion Pink)',
    'SmartWool Hike Light Crew Socks 1-Pack (Dark Blue)',
    'SmartWool Hike Crew Socks 1-Pack (Chestnut Margarita)',
    'SmartWool Hike Crew Socks 1-Pack (Purple Eclipse Margarita)',
    'SmartWool Hike Crew Socks 1-Pack (Deep Navy Margarita)',
    'SmartWool Wintersport Socks 1-Pack (Neo Native Deep Navy)',
    'Jellycat Birdling Dove',
    'Jellycat Harley Hammerhead Shark',
    'Jellycat Pebbles Whale Shark',
    'Jellycat Fleury Pansy',
    'Jellycat Birdling Cardinal',
    'Jellycat Wilf Wolf',
    'Jellycat Dexter Dragon (Little)',
    'Jellycat Bashful Bat (Small)',
    'Jellycat Bashful Beige Bunny (Medium)',
    'Jellycat Boyd Dino (Small)',
    'Jellycat Louie Lion (Little)',
    'Jellycat Odyssey Octopus Soother',
    'Jellycat Scillies Woodruff Wolf',
    'Jellycat Scillies Maple Moose',
    'Jellycat Odyssey Octopus (Baby)',
    'Jellycat Odyssey Octopus Activity Toy',
    'Jellycat Bewitching Bat',
    'Jellycat Amuseable Toadstool (Small)',
    'Jellycat Bashful Puppy (Small)',
    'Jellycat Billie Giraffe (Small)',
    'Jellycat Fuddlewuddle Hippo Soother',
    'Jellycat Fuddlewuddle Elephant Soother',
    'Jellycat Squishy Squash Orange',
    'Yumbox Panino (Nevis Blue)',
    'Yumbox Panino (Neptune Blue)',
    'Yumbox Original (Cilantro Green)',
    'Tegu Magnetic Tram (Rainbow)',
    'Jellycat Bashful Fox Cub (Medium)',
    'Jellycat Sienna Seahorse',
    'ergoPouch Jersey Sleeping Bag 2.5 TOG (Sage)',
    'ergoPouch Jersey Sleeping Bag 2.5 TOG (Night Sky)',
    'Jellycat Zeke Monster',
    'Jellycat Fossilly T-Rex',
    'Jellycat Smudge Fox (Medium)',
    'Jellycat Barnaby Pup (Small)',
    'Jellycat Tia Tiger (Little)',
    'Jellycat Bashful Dragon (Small)',
    'Jellycat Bashful Monkey (Medium)',
    'Jellycat Bashful Grey Bunny (Medium)',
    'ergoPouch Cocoon Swaddle Bag 2.5 TOG (Berries)',
    'Wean Green Lunch Bowl 12oz (Blueberry)',
    'Wean Green Lunch Bowl 12oz (Pea)',
    'Aden + Anais Classic Burpy Bibs 2-Pack (Dahlias)',
    'Plan Toys Rhythm Box',
    'Yumbox Original (Sunburst Yellow)',
    'Rockit Portable Baby Rocker',
    'Chewbeads Juniorbeads Jane Jr. Necklace (Punchy Pink)',
    'Stride Rite Soft Motion Mason Sneaker (Grey/Black)',
    'Stride Rite Willow Boot (Gold)',
    'Stride Rite Soft Motion Milo (Pink)',
    'Stride Rite Soft Motion Milo (Grey)',
    'Lassig Mini Backpack Adventure (Tipi)',
    'Lassig Mini Backpack Adventure (Bus)',
    'Lassig Tiny Backpack About Friends (Racoon)',
    'Lassig Tiny Backpack About Friends (Beaver)',
    'Lassig Tiny Backpack About Friends (Koala)',
    'Lassig Tiny Backpack About Friends (Lion)',
    'Lassig Tiny Backpack About Friends (Bunny)',
    'Lassig Tiny Backpack About Friends (Cat)',
    'Kamik Star 2 Winter Boot (Black)',
    'Kamik Surfer Winter Boot (Medium Grey)',
    'Kamik Star 2 Winter Boot (Charcoal/Orchid)',
    'Kamik Snowbug F Winter Boot (Charcoal/Orchid)',
    'Kamik Snowbug 3 Winter Boot (Olive)',
    'Kamik Snowbug 3 Winter Boot (Blue)',
    'Kamik Snowbug 3 Winter Boot (Rose)',
    'Kamik Snowbug 3 Winter Boot (Black)',
    'Kamik Snobuster 1 Winter Boot (Black)',
    'Kamik Snobuster 1 Winter Boot (Navy)',
    'Kamik Snobuster 1 Winter Boot (Blue)',
    'Stride Rite Soft Motion Mason Sneaker (Tan/Leopard)',
    'Stride Rite Soft Motion Makayla Mary Jane (Black)',
    'Stride Rite Soft Motion Mateo Boot (Sierra)',
    'Stride Rite Soft Motion Kennedy Sneaker (Pink)',
    'Stride Rite Soft Motion Kennedy Sneaker (Taupe/Blue)',
    'Stride Rite Light-Up Cosmic Sneaker (Pink Multi)',
    'Stride Rite Light-Up Fly Away Sneaker (Multi)',
    'Stride Rite Soft Motion Rhett Sneaker (Pink/Purple)',
    'Stride Rite Light-Up Cosmic Sneaker (Navy Multi)',
    'Stride Rite Made2Play Player Sneaker (Pink Multi)',
    'Stride Rite Made2Play Josslyn Sneaker (Blush)',
    'Stride Rite SRT Wes Sneaker Extra Wide (Truffle)',
    'Stride Rite Soft Motion Kennedy Sneaker (Silver Multi)',
    'Stride Rite Soft Motion Kennedy Sneaker (Black)',
    'Stride Rite Soft Motion Amalie Mary Jane (Black)',
    'Stride Rite Soft Motion Kellen Sneaker Extra Wide (Grey)',
    'Jellycat Huggady Elephant (Large)',
    'Jellycat Huggady Dino (Large)',
    'BIBS Pacifier 2 Pack (Sage Night)',
    'Baby Bjorn Bouncer Bliss (Pearly Pink - Mesh)',
    'SmartWool Wintersport Socks 1-Pack (Polar Bear Light Grey)',
    'SmartWool Wintersport Socks 1-Pack (Desert Orchid Stripe)',
    'SmartWool Wintersport Socks 1-Pack (Capri Stripe)',
    'SmartWool Wintersport Socks 1-Pack (Deep Navy Stripe)',
    'SmartWool Wintersport Socks 1-Pack (Medium Gray Stripe)',
    'SmartWool Wintersport Socks 1-Pack (Yo Yetti Light Grey)',
    'SmartWool Wintersport Socks 1-Pack (Light Grey Mountain)',
    'SmartWool Wintersport Socks 1-Pack (Yo Yetti Charcoal)',
    'SmartWool Wintersport Socks 1-Pack (Black Stripe)',
    'SmartWool Wintersport Socks 1-Pack (Purple Eclipse Mountain)',
    'SmartWool Wintersport Socks 1-Pack (Ocean Abyss Mountain)',
    'The North Face Infant Glacier Hoodie (Gravity Purple Dots Print)',
    'The North Face Youth Oh-Mega Fur Pom Beanie (Pikes Purple)',
    'UPPAbaby Knox Convertible Car Seat (Jordan - Charcoal Mélange/Merino Wool)',
    'UPPAbaby Knox Convertible Car Seat (Lucca - Teal Melange)',
    'UPPAbaby Knox Convertible Car Seat (Bryce - White/Grey Marl)',
    'UPPAbaby Knox Convertible Car Seat (Jake - Black)',
    'Plan Toys Big Drum II',
    'Storksak Travel Backpack Changing Bag (Black)',
    'Storksak Travel Shoulder Changing Bag (Black)',
    'Storksak Travel Shoulder Changing Bag (Grey)',
    'Jellycat Dexter Dragon (Large)',
    'LouLou LOLLIPOP Luna Pacifier Clip (Clay)',
    'Jellycat Storm Octopus (Really Big)',
    'Jellycat Bashful Unicorn (Large)',
    'Jellycat Bashful Unicorn (Really Big)',
    'Medela Silicone Breast Milk Collector',
    'SmartWool Toddler Trio Socks 3-Pack (Pink Nectar)',
    'SmartWool Toddler Trio Socks 3-Pack (Ash)',
    'SmartWool Baby Bootie Batch Socks 3-Pack (Ash)',
    'SmartWool Baby Bootie Batch Socks 3-Pack (Meadow Mauve)',
    'SmartWool Baby Bootie Batch Socks 3-Pack (Bright Blue)',
    'SmartWool Baby Bootie Batch Socks 3-Pack (Black)',
    'SmartWool Baby Bootie Batch Socks 3-Pack (Pink Nectar)',
    'SmartWool Baby Bootie Batch Socks 3-Pack (Ocean Abyss)',
    'Yumbox Panino (Go Green)',
    'Yumbox Original (Go Green)',
    'Yumbox MiniSnack (Wow Red)',
    'Yumbox MiniSnack (Misty Aqua)',
    'Yumbox Panino (Misty Aqua)',
    'Yumbox Original (Neptune Blue)',
    'Million Dollar Baby Universal Wide Changing Tray (White)',
    'Million Dollar Baby Universal Wide Changing Tray (Washed Natural)',
    'Nooks Design Merino Wool Cardigan (Sage)',
    'Nooks Design Merino Wool Cardigan (Cherry Blossom)',
    'Nooks Design Embroidered Felted Wool Booties (Cherry Blossom)',
    'Babyletto Hudson Nightstand with USB Port (Washed Natural/White)',
    'Babyletto Hudson Nightstand with USB Port (White)',
    'Babyletto Hudson Nightstand with USB Port (Grey)',
    'Kyte Baby Printed Toddler Blanket 1 TOG (Flamingo)',
    'Kyte Baby Blanket 1 TOG (Oat)',
    'Kyte Baby Blanket 1 TOG (Fog)',
    'Kyte Baby Blanket 1 TOG (Wheat)',
    'Kyte Baby Printed Long Sleeve Zippered Romper (Succulent)',
    'Kyte Baby Long Sleeve Zippered Romper (Midnight)',
    'Kyte Baby Long Sleeve Zippered Romper (Sage)',
    'Kyte Baby Long Sleeve Zippered Romper (Mushroom)',
    'Kyte Baby Long Sleeve Bodysuit (Midnight)',
    'Kyte Baby Long Sleeve Bodysuit (Sage)',
    'Kyte Baby Long Sleeve Bodysuit (Blush)',
    'Kyte Baby Long Sleeve Bodysuit (Oat)',
    'Stork & Dove Booby Boons Lactation Cookies (Cocoa Quinoa)',
    'Babyletto Hudson 6-Drawer Double Dresser (Washed Natural/White)',
    'Babyletto Hudson 6-Drawer Double Dresser (White)',
    'Babyletto Hudson 6-Drawer Double Dresser (Grey)',
    'Storksak Stevie Luxe (Scuba Grey)',
    'Storksak Stevie Luxe (Scuba Black)',
    'Janod Sweet Cocoon Russian Dolls',
    'Bogs Kids Classic (Winter Marble Grey Multi)',
    'Bogs Baby Bogs (Mushrooms Tea Rose Multi)',
    'Manhattan Toy Camp Acorn Photo Book',
    'Manhattan Toy Ball',
    'Nooks Design Embroidered Felted Wool Booties (Golden Spruce)',
    'Nooks Design Embroidered Felted Wool Booties (Rainbow Moon)',
    'The North Face Purrl Stitch Earflap Beanie (Pikes Purple/Gardenia White)',
    'The North Face Toddler Glacier Full-Zip Hoodie (Medium Heather Grey/Black)',
    'The North Face Infant Glacier Hoodie (TNF Medium Grey Heather)',
    'The North Face Toddler Glacier Full-Zip Hoodie (Taupe Green Explorer Camo Print)',
    'The North Face Infant Nuptse One Piece (TNF Black)',
    'The North Face Infant Surgent Crew Set (Peach Pink)',
    'The North Face Toddler Surgent Crew Set (TNF Black)',
    'The North Face Toddler Glacier Full-Zip Hoodie (Gravity Purple Dots Print)',
    "Lulujo Baby's 1st Year Milestone Blanket Set (Greatest Adventure)",
    'MOBY Wrap Classic (Fleck)',
    'Perlimpinpin Bamboo Baby Nightgown (Charcoal)',
    'Tegu 42-Piece Set (Tints)',
    'Kinderfeets Helmet (Matte Rose)',
    'UPPAbaby Bassinet V2 (Greyson - Charcoal Melange)',
    'Tegu Travel Pals (Jet Plane)',
    'Plan Toys Fish Castanet (Yellow)',
    'Plan Toys Fish Castanet (Blue)',
    "Saucony Kid's Ride 10 Jr. Sneaker (Blue/Yellow)",
    'Fridababy Hair Detangler Brush (Fine/Straight Hair)',
    'Fridababy Hair Detangler Brush (Thick/Curly Hair)',
    'Little Lunchbox Co. Bento Cups Rectangle (Light Blue)',
    'Little Lunchbox Co. Bento Cups Square (Light Blue)',
    'Little Lunchbox Co. Bento Cups Square (Green)',
    "Saucony Kid's Ride 10 Jr. Sneaker (Olive Camo)",
    "Saucony Kid's Ride 10 Jr. Sneaker (Navy/Pink Camo)",
    'Petunia Pickle Bottom Nimble Changer Clutch (Neo Geo)',
    'Petunia Pickle Bottom Nimble Changer Clutch (Leopard)',
    'Petunia Pickle Bottom City Carryall (Black Matte Leatherette)',
    'Petunia Pickle Bottom Axis Backpack (Birch/Black)',
    'Petunia Pickle Bottom Inter-Mix Slope Backpack (Birch/Black)',
    'Petunia Pickle Bottom Pivot Pack (Smoke Swirl Tie-Dye)',
    'Petunia Pickle Bottom Meta Backpack (Graphite/Black)',
    'Petunia Pickle Bottom Meta Backpack (Black Matte Canvas)',
    'Jellycat Pet Tails Book',
    'Jellycat Jungly Tails Book',
    'The North Face Toddler Camp Fleece Set (New Taupe Green)',
    'The North Face Toddler Camp Fleece Set (Pearl Blush)',
    'Fluf Zipper Lunch Bag (Happy Bread/Mint)',
    'Vignette Charlie Dress (Leaf)',
    'Vignette Anne Dress (Burgundy)',
    'Vignette Paige Dress (Rose)',
    'Vignette Mary Playsuit (Rose Star)',
    'Vignette Avery Blouse (Rose Floral)',
    'Vignette Daisy Bubble (Rose Floral)',
    'Vignette Peyton Top (Rust)',
    'Vignette Jenna Romper (Navy)',
    'Vignette Everly Romper (Grey)',
    'Vignette Everly Romper (Gold)',
    'Vignette Mae Vest (Cream)',
    'Vignette Quinn Onesie (Grey)',
    'Vignette Quinn Onesie (Rose)',
    'Vignette Quinn Onesie (Burgundy)',
    'Vignette Quinn Onesie (Navy)',
    'Vignette Quinn Onesie (Cream)',
    'Fluf B Pack Backpack (Mauve/Pink)',
    'Munchbox Mega3 (Deep Space)',
    'Munchbox Mini4 Extra Tray (Clear)',
    'Munchbox Mini4 Extra Tray (Artwork)',
    'Munchbox Midi5 Extra Tray (Clear)',
    'Munchbox Midi5 Extra Tray (Artwork)',
    'Munchbox Mega4 Extra Tray (Clear)',
    'Munchbox Mega3 Extra Tray (Clear)',
    'Munchbox Mega3 Extra Tray (Artwork Space)',
    'Munchbox Maxi6 Extra Tray (Clear)',
    'Munchbox Maxi6 Extra Tray (Artwork)',
    'Munchbox Munchi Snack (Seaside Blue)',
    'Munchbox Munchi Snack (Purple Periwinkle)',
    'Munchbox Munchi Snack (Pink Sunset)',
    'Munchbox Munchi Snack (Peppermint Blush)',
    'Munchbox Munchi Snack (Lime Soda)',
    'Munchbox Munchi Snack (Blue Storm)',
    'Munchbox Mega4 (#fuschiatint)',
    'Munchbox Mega4 (#electricblue)',
    'Munchbox Mega3 (Milky Way)',
    'Munchbox Mega3 (Galaxy)',
    'Munchbox Maxi6 (Purple Peacock)',
    'Munchbox Maxi6 (Pink Princess)',
    'Munchbox Maxi6 (Midnight Blue)',
    'Munchbox Maxi6 (Green Jungle)',
    'Munchbox Maxi6 (Blue Ocean)',
    'Munchbox Midi5 (Yellow Lemonade)',
    'Munchbox Midi5 (Lavender Dream)',
    'Munchbox Midi5 (Bubblegum Mint)',
    'Munchbox Midi5 (Blue Coco)',
    'Munchbox Mini4 (The Redback)',
    'Munchbox Mini4 (The Outback)',
    'Munchbox Mini4 (Berry Blitz)',
    'Fluf Zipper Lunch Bag (Solid Black/Tan)',
    'Fluf Zipper Lunch Bag (Lunch Mauve/Pink)',
    'Fluf Zipper Lunch Bag (Lunch Blue)',
    'Fluf Zipper Lunch Bag (Block Poppy Mango)',
    'Fluf Zipper Lunch Bag (Block Navy Mango)',
    'Fluf Zipper Lunch Bag (Fox)',
    'Little Lunchbox Co. Bento Five (Grey)',
    'Little Lunchbox Co. Bento Three (Black)',
    'Little Lunchbox Co. Bento Three (Purple)',
    'Little Lunchbox Co. Bento Two (Pink)',
    'Little Lunchbox Co. Bento Five (Mint)',
    'Little Lunchbox Co. Bento Two (Mint)',
    'Little Lunchbox Co. Bento Two (Ninja)',
    'Little Lunchbox Co. Bento Two (Shark)',
    'Little Lunchbox Co. Bento Five (Ninja)',
    'Kyte Baby Knotted Cap (Oat)',
    'Me & Henry Bradford Pants with Removable Suspenders (Black Dogtooth)',
    'Kyte Baby Sleep Bag 2.5 TOG (Emerald)',
    'Kyte Baby Sleep Bag 2.5 TOG (Slate)',
    'Kyte Baby Printed Zippered Footie (Aloe Rainbow)',
    "Kyte Baby Women's Jogger Pajama Set (Fog)",
    "Kyte Baby Women's Jogger Pajama Set (Mushroom)",
    'Jellycat Charley Cheetah (Little)',
    'Jellycat Nessie (Huge)',
    'Jellycat Huggady Elephant (Medium)',
    'Jellycat Huggady Dino (Medium)',
    'Jellycat Storm Octopus (Baby)',
    'Jellycat Garden Tails Book',
    'Thermos FUNtainer Water Bottle 12oz (Lime)',
    'Thermos FUNtainer Stainless Steel Water Bottle with Spout 16oz (Seafoam)',
    'MOBY Wrap Classic (Black)',
    'MOBY Wrap Evolution (Batik)',
    'MOBY Wrap Evolution (Caramel)',
    'MOBY Wrap Evolution (Charcoal)',
    'MOBY Wrap Evolution (Denim)',
    'MOBY Wrap Evolution (Lattice)',
    'MOBY Wrap Evolution (Vanilla)',
    'MOBY Ring Sling (Silver Streak)',
    'MOBY Ring Sling Double Gauze (Rose)',
    'Petunia Pickle Bottom Boxy Backpack (Black Matte Leatherette)',
    'Petunia Pickle Bottom Boxy Backpack (Graphite/Black)',
    'Jellycat Sea Tails Book',
    'Boon Prance Silicone Teether',
    'Jellycat Beatrice Butterfly (Huge)',
    'Jellycat Bashful Turtle (Small)',
    'Jellycat Bashful Grey Bunny (Large)',
    'Thule Sapling Sling Pack',
    'BIBS Couture Latex Pacifier 2 Pack (Blush)',
    'Colibri Reusable Snack Bag Small (Sharks)',
    'Colibri Reusable Snack Bag Large (Fairy Tale)',
    'Piggy Paint Water-Based Nail Polish Set (Funny Bunny)',
    'Piggy Paint Water-Based Nail Polish (Sea-quin)',
    'Piggy Paint Water-Based Nail Polish (Groovy Grape)',
    'Piggy Paint Water-Based Nail Polish (Blueberry Patch)',
    'Saucony Peregrine 11 Shield A/C Sneaker (Turquoise/Multi)',
    'Ezpz Mini Mat (Grey)',
    'BapronBaby Bapron Toddler Bib (Outer Space)',
    'BapronBaby Bapron Toddler Bib (Desert Cactus)',
    'Jellycat Bumbly Bear (Medium)',
    'Stride Rite Cassie Sandal (Light Pink)',
    'Stride Rite Soft Motion Sophie Cozy Boot (Light Gold)',
    'Stride Rite Wave Sneaker Sandal (Pink Multi)',
    'Jellycat Blossom Blush Bunny (Medium)',
    'Jellycat Blossom Jasmine Bunny 12"',
    'Jellycat Bashful Tulip Pink Bunny (Small)',
    'Jellycat Bashful Unicorn (Small)',
    'Jellycat Bashful Panda (Small)',
    'Jellycat Bashful Otter (Small)',
    'Jellycat Bashful Cream Bunny (Small)',
    'Jellycat Harry Panda Cub (Large)',
    'Jellycat Amuseable Toadstool (Large)',
    'Jellycat Bashful Lion (Huge)',
    'Jellycat Bashful Fudge Puppy (Huge)',
    'Jellycat Odell Octopus (Baby)',
    'Jellycat Amuseable Desert Cactus (Small)',
    'Jellycat Amuseable Pineapple (Small)',
    'Jellycat Louie Lion (Huge)',
    'Jellycat Billow Manatee',
    'Jellycat Douglas Dino (Little)',
    'Jellycat Birdling Kingfisher',
    'Jellycat Birdling Blue Tit',
    'Jellycat Finley Bear (Small)',
    'Jellycat Fleury Sunflower',
    'Jellycat Brooklyn Hippo (Small)',
    'Jellycat Carey Calf (Medium)',
    'Jellycat Boiled Egg Blushing',
    'Jellycat Pandy Chimpanzee',
    'Jellycat Gorka Gecko',
    'Jellycat Charley Cheetah (Medium)',
    'Jellycat Seymour Bear',
    'Jellycat Gamboldown Cow (Large)',
    'Thule Sapling (Agave)',
    'Baby Bjorn Harmony Carrier 3D Mesh (Silver)',
    'Baby Bjorn Step Stool (Deep Blue/White)',
    'Baby Bjorn Baby Carrier One Air (Silver)',
    'Me & Henry Brent Baby Pants (Black)',
    'Me & Henry Atwood Woven Shirt (Black/White Plaid)',
    'Me & Henry Doyle Tee (Charcoal/Multi Stripe)',
    'Me & Henry Flagstop Henley Tee (Grey Stripe)',
    'Me & Henry Cowan Tee (Black/White Stripe)',
    'Me & Henry Alcoa Tee (Loden Green Stripe)',
    'Me & Henry Alcoa Tee (Gold Stripe)',
    'Me & Henry Gleason Jersey Overalls (Blue)',
    'Baby Bjorn Bouncer Toy (Googly Eyes Pastels)',
    'Me & Henry Arlington Polo Romper (Charcoal/Grey Stripe)',
    'Me & Henry Arlington Polo Romper (Rust/Navy Stripe)',
    'Me & Henry Ripley Jersey Romper (Grey/White Stripe)',
    'Me & Henry Niota Henley Romper (Blue/Navy Stripe)',
    'Me & Henry Niota Henley Romper (Black/Grey Stripe)',
    'Me & Henry Blaine Hooded Romper (Green/Grey Multi Stripe)',
    'Me & Henry Stanton Henley Onesie (Black/White Stripe)',
    'Me & Henry Stanton Henley Onesie (Brown/White Stripe)',
    'Me & Henry Jasper Woven Onesie (Brown/Rust Plaid)',
    'Me & Henry Jasper Woven Onesie (Navy/Cream/Wine Plaid)',
    'Me & Henry Jasper Woven Onesie (Black/White/Red Plaid)',
    'Me & Henry Gleason Jersey Overalls (Black)',
    'The North Face Toddler Glacier Full-Zip Hoodie (TNF Medium Grey Heather)',
    'Me & Henry Pablo Playsuit (Grey/White Stripe)',
    'Me & Henry Ahoy Shortie Overalls (Grey Stripe)',
    'Me & Henry Flagstaff Polo Shirt (Grey/White Stripe)',
    'Me & Henry Saltash Polo Romper (Grey/White)',
    'Me & Henry Bowline Shortie Overalls (Beige)',
    'Me & Henry Helford Short Sleeved Onesie (Chambray)',
    'Me & Henry Helford Short Sleeved Onesie (Blue/Red Plaid)',
    'Schleich Off-Road Vehicle with Dino Outpost',
    "Schleich Horse Club Hannah's Guest Horses with Ruby the Dog",
    'Bruder MAN TGS Street Sweeper',
    'Bruder MB Sprinter UPS with Driver',
    'Bruder MACK Granite Garbage Truck',
    'Bruder MACK Granite Fire Engine with Water Pump - IN STORE PICK UP ONLY',
    "Schleich Horse Club Lisa's Tournament Training",
    'Bruder Mercedes Benz Sprinter Animal Transporter with Horse',
    'Schleich Pachycephalosaurus',
    'Schleich Mandala Unicorn Mare',
    'Schleich Foal With Blanket',
    'Kaloo Tendress Rose Doll (Medium)',
    'Bruder Scrambler Ducati Full Throttle with Driver',
    'Bruder Tandemaxle Tipping Trailer with Removeable Top',
    'Bruder bWorld Police Station with Police Motorcycle',
    'Schleich Tarantula',
    'Schleich Giant Panda Male',
    'Schleich Acrocanthosaurus',
    'Schleich Drake',
    'Kamik Stomp Rain Boot (Olive)',
    'Kamik Cozylodge Slipper (Red/Black)',
    'Kamik Cozylodge Slipper (Pink)',
    'Schleich Blind Bag (Wild Life 21)',
    'Stride Rite Light-Up Glimmer Sneaker (Silver/Pink)',
    'Schleich Blind Bag (Horse Club 21)',
    'Bruder Schäffer Compact Loader 2034',
    'Kamik Cozylodge Slipper (Black/Charcoal)',
    'Janod Lapin Carrot Car',
    'Plus Plus Tube Pastel 240 Pieces',
    'Plus Plus Tube Basic 240 Pieces',
    'Plus Plus Tube 70+ Pieces (Bumblebee)',
    'Plus Plus Tube 70+ Pieces (Cow)',
    'Momma Goose Baltic Amber Teething Necklace (Spearhead)',
    'Momma Goose Baltic Amber Teething Necklace (Iago)',
    'Momma Goose Baltic Amber Teething Necklace (Diavolo)',
    'Momma Goose Baltic Amber Teething Necklace (Fitzsimmons)',
    'Schleich Fairy in Flight on Winged Lion',
    'Schleich Fairy in Flight on Glam-Owl',
    'Schleich Blind Bag (Farm World 21)',
    'Oxo Tot Sprout High Chair Replacement Cushion Set (Taupe)',
    'Oxo Tot Sprout High Chair Replacement Cushion Set (Navy)',
    'Oxo Tot Sprout Chair (Grey/Green) FLOOR MODEL',
    'Oxo Tot Sprout Chair (Walnut/Navy)',
    'Oxo Tot Sprout Chair (Birch/Navy)',
    'Oxo Tot Sprout Chair (Birch/Taupe)',
    'Oxo Tot Sprout Chair (Walnut/Taupe)',
    'Oxo Tot Sprout Chair (Walnut/Grey)',
    'Oxo Tot Sprout Chair (Grey/Grey)',
    'LouLou LOLLIPOP Top Knot Beanie Hat (Slate)',
    'LouLou LOLLIPOP Stretch Knit Swaddle Blanket (Slate)',
    'LouLou LOLLIPOP Stretch Knit Swaddle Blanket (Sage)',
    'LouLou LOLLIPOP Stretch Knit Swaddle Blanket (Flower Vine)',
    'LouLou LOLLIPOP Muslin Single Swaddle (Quebec)',
    'LouLou LOLLIPOP Luna Pacifier Clip (Coral)',
    'LouLou LOLLIPOP Teether Set (Sloth Gem)',
    'LouLou LOLLIPOP Teether Set (Llama Gem)',
    'LouLou LOLLIPOP Teether Set (Avocado)',
    'LouLou LOLLIPOP Lolli Silicone Pacifier Clip (Blue Mint)',
    'LouLou LOLLIPOP Lolli Silicone Pacifier Clip (Cotton Candy)',
    'LouLou LOLLIPOP Colour Block Silicone & Wood Pacifier Clip (Dusty Rose)',
    'BIBS Baby Bitie Star (Ivory)',
    'BIBS Baby Bitie Heart (Mustard)',
    'BIBS Baby Bitie Heart (Peach)',
    'BIBS Cuddle Cloth Muslin 2-Pack (Mustard)',
    'BIBS Cuddle Cloth Muslin 2-Pack (Sage)',
    'BIBS Baby Bitie Star (Baby Blue)',
    'BIBS Baby Bitie Star (Blush)',
    'BIBS Baby Bitie Heart (Sage)',
    'BIBS Cuddle Cloth Muslin 2-Pack (Blush)',
    'BIBS Cuddle Cloth Muslin 2-Pack (Ivory)',
    'Schleich Vet Visiting Mare & Foal',
    'Schleich Paddock with Entry Gate',
    'Schleich African Elephant Female',
    'Lulujo Waffle Blanket (Sand)',
    'Lulujo Waffle Blanket (Ballet Slipper)',
    'Só Luxury Salty Eucalyptus Rose (800g)',
    'Só Luxury Salty Island Coconut (800g)',
    'Fridababy Grooming Kit',
    'Bruder MB Arocs Snow Plow Truck',
    'Ubabub Nifty 3-Drawer Dresser (Natural Birch)',
    'Ubabub Nifty 3-Drawer Dresser (Walnut)',
    'Ubabub Nifty Timber 3-in-1 Convertible Crib (Natural Birch)',
    'Ubabub Nifty Timber 3-in-1 Convertible Crib (Walnut)',
    'Franklin & Ben Emory Farmhouse 4-in-1 Convertible Crib (Linen White)',
    'Franklin & Ben Emory Farmhouse 4-in-1 Convertible Crib (Driftwood Finish)',
    'Franklin & Ben Toddler Bed Conversion Kit (Driftwood Finish)',
    'Franklin & Ben Emory Farmhouse 6-Drawer Dresser (Driftwood Finish)',
    'Schleich Fairy Feya with Pegasus Unicorn',
    'Schleich Quarter Horse Stallion',
    "Dr. Brown's Natural Flow Deluxe Baby Bottle Sterilizer",
    'Franklin & Ben Emory Farmhouse 3-in-1 Convertible Crib (Driftwood Finish)',
    'Haakaa Silicone Shampoo Brush (Grey)',
    'Haakaa Silicone Baby Drinking Cup (Rust)',
    'Haakaa Silicone Baby Drinking Cup (Bluestone)',
    'Haakaa Silicone Baby Drinking Cup (Sueva Grey)',
    'Haakaa Silicone Baby Drinking Cup (Blush)',
    'Deux par Deux Puffer 1-Piece Snowsuit (Anthracite)',
    'Deux par Deux Puffer 1-Piece Snowsuit (Bordeaux)',
    'Fat Brain Toys Spin Again',
    'Babyletto Origami Mini Crib (Lagoon)',
    'Glitter & Spice Silicone Bear Cup (Seafoam)',
    'Glitter & Spice Silicone Bear Cup (Blush)',
    'Glitter & Spice Silicone Bear Cup (Black)',
    'Glitter & Spice Silicone Bowl & Spoon Set (Midnight Blue)',
    'Glitter & Spice Silicone Bowl & Spoon Set (Black)',
    'Jellycat Odyssey Octopus (Large)'
];

let uniqueItems = [];
let iterate = 0;

ht.map((item) => {
    if (!uniqueItems.includes(item)) {
        uniqueItems.push(item);
    } else {
        iterate++;
    }

    return true;
});

console.log('uniqueItems:', uniqueItems.length, iterate);