export const buckets = {
    'Healing Hollow': [ 'Beauty' ],
    'Baby and Me': [ 'Baby & Kids' ],
    'Funktional': [ 'Omit this shop' ],
    'Salt and Sage': [ 'Bohemian' ],
    'Galibelle Canada': [ 'Trendy' ],
    'Boheme Collective': [ 'Bohemian' ],
    'SWWAY': [ 'Casual' ],
    'Louise Estelle': [ 'Accessories' ],
    'Play Stores': [ 'Athletic' ],
    'Man + Woman': [ 'Trendy' ],
    'Portia Ella': [ 'Beauty' ],
    'Loyal Hair': [ 'Beauty' ],
    'Set 4 Lyfe': [ 'Music Festival' ],
    'Scopey': [ 'Casual' ],
    'Leoella': [ 'Omit this shop' ],
    '6am Work Shirts': [ 'Omit this shop' ],
    'Freeride Boardshop': [ 'Casual' ],
    'Elizabeth O. Vintage': [ 'Vintage' ],
    'Elliott Row': [ 'Chic' ],
    'Something Pretty Boutique': [ 'Casual' ],
    'ad hoc': [ 'Trendy' ],
    'Without A Doubt Day Spa': [ 'Beauty' ],
    'The Homemade Organics Company': [ 'Beauty' ],
    'Big Sun': [ 'Casual' ],
    'Merchant logo\nBirch Hill Studio': [ 'Casual' ],
    'Back to Earth': [ 'Beauty' ],
    '1000 palms swimwear': [ 'Bohemian' ],
    'Okanagan Lifestyle': [ 'Casual' ],
    'Lox and Fox Baby Boutique': [ 'Baby & Kids' ],
    'Frakas': [ 'Chic' ],
    'Beach Ave': [ 'Trendy' ],
    'Resfeber Lifestyle Apparel': [ 'Casual' ],
    'SIMS Jewelry Co.': [ 'Accessories' ],
    'Lost Together': [ 'Vintage' ],
    'The Handmade Shoppe': [ 'Casual', 'Accessories', 'Beauty' ],
    'Blue Sky Clothing: Kelowna': [ 'Casual' ],
    'Aldila Boutique': [ 'Chic' ],
    'Unhinged Gift & Lifestyle Boutique': [ 'Casual', 'Accessories', 'Beauty' ],
    'Castanet Apparel': [ 'Omit this shop' ],
    'Sweetlegs Clothing Inc.': [ 'Athletic' ],
    'Au Canada Apparel': [ 'Casual' ],
    'Del Lago': [ 'Trendy' ],
    'Foursight Supply Co.': [ 'Casual', 'Accessories' ],
    'Cruzwear Unlimited': [ 'Casual' ],
    'Grey Hearts Denim': [ 'Casual', 'Accessories' ],
    'The Bumwrap': [ 'Casual', 'Accessories' ],
    'Bubba and Blue': [ 'Baby & Kids' ],
    'Daisy & Jane Clothiers': [ 'Vintage' ],
    'MOGANO': [ 'Accessories' ],
    'lolo and spence ': [ 'Baby & Kids' ]
};